local cards = {
    {
        name = "Corbak",
        imagePath = "Art/corback",
        hp = 1,
        attack = 1,
        type = "NORMAL",
        rarity = "COMMON",
    },
    {
        name = "Ewink",
        imagePath = "Art/ewink",
        hp = 1,
        attack = 2,
        type = "NORMAL",
        rarity = "COMMON",
    },
    {
        name = "Gostears",
        imagePath = "Art/gostears",
        hp = 2,
        attack = 2,
        type = "NORMAL",
        rarity = "COMMON",
    },
    {
        name = "Hurtouk",
        imagePath = "Art/hurtouk",
        hp = 2,
        attack = 2,
        type = "NORMAL",
        rarity = "COMMON",
    },
    {
        name = "Lonelink",
        imagePath = "Art/lonelink",
        hp = 2,
        attack = 1,
        type = "NORMAL",
        rarity = "COMMON",
    },
    {
        name = "Panink",
        imagePath = "Art/panink",
        hp = 3,
        attack = 1,
        type = "NORMAL",
        rarity = "RARE",
    },
    {
        name = "Satanink",
        imagePath = "Art/satanink",
        hp = 2,
        attack = 2,
        type = "NORMAL",
        rarity = "COMMON",
    },
    {
        name = "Shuffly",
        imagePath = "Art/shuffly",
        hp = 6,
        attack = 0,
        type = "NORMAL",
        rarity = "EPIC",
    },
    {
        name = "Zombaxe",
        imagePath = "Art/zombaxe",
        hp = 2,
        attack = 1,
        type = "NORMAL",
        rarity = "COMMON",
    },
    {
        name = "Mr.Ink",
        imagePath = "Art/mrink",
        hp = 3,
        attack = 2,
        type = "NORMAL",
        rarity = "RARE",
    },
}

function RegisterCards()
    return cards
end
